### PR TITLE
[#137357707] Adjusted the router LB health check thresholds to accoun…

### PR DESCRIPTION
**Pull request by pdelagrave**
…t for GCP networking unreliabilities

Signed-off-by: Nitin Ravindran <nravindran@pivotal.io>

### CODE REVIEW

**Comment by ryanmoran** [comment]
@pdelagrave I would like to see some confirmation that this resolves this issue for you. We haven't seen anything like what you are describing, and have found the GCP network to be quite stable.

**Comment by pdelagrave** [comment]
Sure, we'll use the patched branch for a week and come back with feedback

**Comment by zachgersh** [comment]
@pdelagrave do we still need to merge this?

**Comment by pdelagrave** [comment]
The (late) feedback about it is: it didn't solve the issue, maybe helped a bit as we saw a less occurrences of the problem but it's still there. This PR can be closed.

The problem we're having, for reference:
https://www.pivotaltracker.com/story/show/138756685

**Pull request closed without merging**
