### PR TITLE
New Feature: template for GCP tile configuration

### PR DESCRIPTION
**Pull request by paulczar**
This adds a template file and resource for rendering out a file
that contains all of the relevent settings for configuring the
GCP tile in Operations Manager.

### CODE REVIEW

**Comment by paulczar** [comment]
example rendered file contents:

```
# Operations Manager GCP Tile Config

## Google Config
Project ID: XXXXX
Default Deployment Tag: pivlab-vms
AuthJSON: { XXXXX }


## Director Config
NTP Servers: metadata.google.internal
[x] Enable VM Resurrector Plugin
[x] Enable Post Deploy Scripts
Blobstore Location: Internal
Database Location: Internal

## Create Availability Zones
us-central1-a,us-central1-b,us-central1-c

## Create Networks

### Management Subnet:
Name: pivlab-management-subnet
Google Network Name: pivlab-pcf-network/pivlab-management-subnet/us-central1
CIDR: 10.0.0.0/26
Reserved IP Ranges: 10.0.0.1-10.0.0.9
DNS: 169.254.169.254
Gateway: 10.0.0.1
Availability Zones: us-central1-a,us-central1-b,us-central1-c

### PAS Subnet:
Name: pivlab-pas-subnet
Google Network Name: pivlab-pcf-network/pivlab-pas-subnet/us-central1
CIDR: 10.0.4.0/24
Reserved IP Ranges: 10.0.4.1-10.0.4.9
DNS: 169.254.169.254
Gateway: 10.0.4.1
Availability Zones: us-central1-a,us-central1-b,us-central1-c

### PAS Services Subnet:
Name: pivlab-services-subnet
Google Network Name: pivlab-pcf-network/pivlab-services-subnet/us-central1
CIDR: 10.0.8.0/24
Reserved IP Ranges: 10.0.8.1-10.0.8.9
DNS: 169.254.169.254
Gateway: 10.0.8.1
Availability Zones: us-central1-a,us-central1-b,us-central1-c

### PKS Subnet:
Name: pivlab-pks-subnet
Google Network Name: pivlab-pcf-network/pivlab-pks-subnet/us-central1
CIDR: 10.0.10.0/24
Reserved IP Ranges: 10.0.10.1-10.0.10.9
DNS: 169.254.169.254
Gateway: 10.0.10.1
Availability Zones: us-central1-a,us-central1-b,us-central1-c

### PKS Services Subnet:
Name: pivlab-pks-services-subnet
Google Network Name: pivlab-pcf-network/pivlab-pks-services-subnet/us-central1
CIDR: 10.0.11.0/24
Reserved IP Ranges: 10.0.11.1-10.0.11.9
DNS: 169.254.169.254
Gateway: 10.0.11.1
Availability Zones: us-central1-a,us-central1-b,us-central1-c

## Assing AZs and Networks
Singleton Availability Zone: us-central1-a
Network: pivlab-management-subnet

## Security

Download the CA cert from `Operations Manager -> Settings -> Advanced` and paste the contents into here.

## Resource Config

Ensure all resources are "internet connected"
```

**Comment by jtarchie** [comment]
This seems like a very specific checklist or document for a workflow. For example, `Ensure all resources are "internet connected"`.

What information are you trying to get out of terraform that the outputs don't provide?

**Comment by paulczar** [comment]
@jtarchie I'm not looking for any new information, just re-organizing the output to match defaults from the install docs, and the configuration forms in operations manager so that you don't have to hunt for specific values in a randomly ordered list of keys/values in terraform output.

**Comment by joshzarrabi** [comment]
Hi @paulczar, sorry for the delayed response. I think this is a really interesting idea, and is definitely something we need to work on. I think perhaps a better option for the template is something that `om` could use to configure the tile directly. For an example check out our pipeline, where we essentially create this template in a concourse task. 

Here we have a [go template file](https://github.com/cloudfoundry/infrastructure-ci/blob/master/scripts/terraforming/gcp/upload-configure-stage/config-director-template.yml) which expects a [transformed version](https://github.com/cloudfoundry/infrastructure-ci/blob/f2389b77a6d26b0c5acbb02fc76573e3ac4554d7/scripts/terraforming/gcp/upload-configure-stage/task#L6-L8) of the terraform output as an input, and fills in the templated out fields using the [texplate](https://github.com/pivotal-cf/texplate) tool, which is a light wrapper around [go templating](https://golang.org/pkg/text/template/). This is where we fill in the template https://github.com/cloudfoundry/infrastructure-ci/blob/f2389b77a6d26b0c5acbb02fc76573e3ac4554d7/scripts/terraforming/gcp/upload-configure-stage/task#L19.  The outputted file is ready for `om configure-product`. 

We like this solution because om can read the file directly to configure the tile, so we can fully automate our pcf install. 

Would something like this make sense for your use case?

**Comment by davewalter** [comment]
@joshzarrabi `om configure-product` can now interpolate variables itself, so you don't even need to use texplate. It also understands ops-files...

**Comment by joshzarrabi** [comment]
@davewalter Wow!

**Comment by jtarchie** [comment]
What's textplate?

**Comment by joshzarrabi** [comment]
@jtarchie Its a small go wrapper cli around go text templating written by @ljfranklin. It provides a nice cli with syntactic sugar around templating.

**Comment by paulczar** [comment]
My goal was to iterate on this until it was good enough to fully automate opsman and then do something along the lines of what you're suggesting to fully automate the whole thing.  However even then I don't think its a bad thing to have a configuration document that shows exactly how the tile should be configured.

**Comment by paulczar** [comment]
I keep seeing people unsure of settings to use in Ops Manager, especially the trickier stuff like the network names ...  I really think this PR will be helpful to people.  Given its not really affecting functionality and just increasing outputs I'd like to see it get moving.

**Comment by joshzarrabi** [comment]
@paulczar We would really like to see it fully automatable before we merge it. I think it makes a lot of sense for it to output a template that `om` knows how to fill in and apply. We would be happy to discuss doing this as a team, as I do think it would make the user experience a lot better.

**Comment by paulczar** [comment]
@joshzarrabi how goes the automation effort to have OM configure-product word with the terraform output?  If its done can you point to documentation on using ?

**Comment by zachgersh** [comment]
hey @paulczar - unsure what the status of this is. Maybe we can convene a little discussion with us and @pivotal-cf/pcf-platform-automation to discuss how to work this into `om` as mentioned earlier.

**Pull request closed without merging**
